version: "3"

services:
  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/developer/dev/db/:/data/db
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    depends_on:
        - mongo
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongo:27017
